const express = require('express');
const router = express.Router();
const { Pool } = require('pg');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { v4: uuidv4 } = require('uuid');
const axios = require('axios');

const pool = new Pool({
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  user: process.env.DB_USER || 'digzio_admin',
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  ssl: { rejectUnauthorized: false }
});

const s3Client = new S3Client({ region: process.env.AWS_REGION || 'af-south-1' });
const BUCKET_NAME = process.env.S3_BUCKET;
const NOTIFICATION_URL = process.env.NOTIFICATION_URL || 'http://digzio-notification-service-prod:3004/api/v1/notifications/email';

const mockAuth = (req, res, next) => {
  req.user = { id: req.headers['x-user-id'] || '1', role: req.headers['x-user-role'] || 'provider' };
  next();
};

// Generate Lease PDF
async function generateLeasePDF(data) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4 size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  
  const text = `
    DIGZIO LEASE AGREEMENT
    
    Date: ${new Date().toLocaleDateString()}
    
    LANDLORD: ${data.provider_name}
    TENANT: ${data.tenant_name}
    PROPERTY: ${data.property_title}
    LOCATION: ${data.property_location}
    
    MONTHLY RENT: ZAR ${data.rent_amount}
    DEPOSIT: ZAR ${data.deposit_amount}
    START DATE: ${data.start_date}
    END DATE: ${data.end_date}
    
    This is a legally binding document generated by Digzio.
  `;
  
  page.drawText(text, { x: 50, y: 750, size: 12, font, color: rgb(0, 0, 0) });
  return await pdfDoc.save();
}

// 1. Generate and Send Lease (Provider)
router.post('/generate', mockAuth, async (req, res) => {
  try {
    if (req.user.role !== 'provider') return res.status(403).json({ error: 'Only providers can generate leases' });

    const { application_id, start_date, end_date, rent_amount, deposit_amount } = req.body;

    // Fetch data for lease
    const dataQuery = await pool.query(
      `SELECT a.tenant_id, p.id as property_id, p.title as property_title, p.location as property_location,
              u_tenant.first_name || ' ' || u_tenant.last_name as tenant_name, u_tenant.email as tenant_email,
              u_provider.first_name || ' ' || u_provider.last_name as provider_name
       FROM applications a
       JOIN properties p ON a.property_id = p.id
       JOIN users u_tenant ON a.tenant_id = u_tenant.id
       JOIN users u_provider ON p.provider_id = u_provider.id
       WHERE a.id = $1 AND p.provider_id = $2`,
      [application_id, req.user.id]
    );

    if (dataQuery.rows.length === 0) return res.status(404).json({ error: 'Application not found or unauthorized' });
    const data = dataQuery.rows[0];

    // Generate PDF
    const pdfBytes = await generateLeasePDF({ ...data, start_date, end_date, rent_amount, deposit_amount });
    
    // Upload to S3
    const fileId = uuidv4();
    const s3Key = `leases/${fileId}.pdf`;
    
    await s3Client.send(new PutObjectCommand({
      Bucket: BUCKET_NAME,
      Key: s3Key,
      Body: pdfBytes,
      ContentType: 'application/pdf'
    }));

    const documentUrl = `https://${process.env.CLOUDFRONT_DOMAIN}/${s3Key}`;

    // Create lease record
    const leaseResult = await pool.query(
      `INSERT INTO leases (property_id, tenant_id, application_id, start_date, end_date, rent_amount, deposit_amount, document_url, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending_signature')
       RETURNING *`,
      [data.property_id, data.tenant_id, application_id, start_date, end_date, rent_amount, deposit_amount, documentUrl]
    );

    // Notify tenant
    try {
      await axios.post(NOTIFICATION_URL, {
        to: data.tenant_email,
        subject: 'New Lease Agreement to Sign',
        body_html: `<p>A new lease agreement is ready for you to sign on Digzio. <a href="${documentUrl}">View Lease</a></p>`,
        body_text: `A new lease agreement is ready for you to sign on Digzio. View here: ${documentUrl}`
      });
    } catch (err) {
      console.error('Failed to send notification', err.message);
    }

    res.status(201).json(leaseResult.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate lease' });
  }
});

// 2. Sign Lease (Tenant)
router.patch('/:id/sign', mockAuth, async (req, res) => {
  try {
    if (req.user.role !== 'student') return res.status(403).json({ error: 'Only students can sign leases' });

    const { id } = req.params;

    const result = await pool.query(
      `UPDATE leases SET status = 'active', signed_at = NOW() 
       WHERE id = $1 AND tenant_id = $2 RETURNING *`,
      [id, req.user.id]
    );

    if (result.rows.length === 0) return res.status(404).json({ error: 'Lease not found or unauthorized' });

    res.json(result.rows[0]);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to sign lease' });
  }
});

// 3. Get my leases
router.get('/my', mockAuth, async (req, res) => {
  try {
    const roleColumn = req.user.role === 'student' ? 'tenant_id' : 'provider_id';
    
    let query = `SELECT l.*, p.title, p.location FROM leases l JOIN properties p ON l.property_id = p.id WHERE l.${roleColumn} = $1`;
    
    if (req.user.role === 'provider') {
      query = `SELECT l.*, p.title, p.location FROM leases l JOIN properties p ON l.property_id = p.id WHERE p.provider_id = $1`;
    }

    const result = await pool.query(query, [req.user.id]);
    res.json(result.rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to fetch leases' });
  }
});

module.exports = router;
